/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddLandForm: typeof import('./src/components/land/add-land-form.vue')['default']
    AddLandFormModal: typeof import('./src/components/land/add-land-form-modal/index.vue')['default']
    copy: typeof import('./src/components/land/add-land-form-modal/index copy.vue')['default']
    CreatePlan: typeof import('./src/components/task/CreatePlan.vue')['default']
    DeviceFirmwareStatus: typeof import('./src/components/devices/DeviceFirmwareStatus.vue')['default']
    DeviceFirmwareUpgrade: typeof import('./src/components/devices/device-upgrade/DeviceFirmwareUpgrade.vue')['default']
    DeviceFirmwareUpgradeModal: typeof import('./src/components/devices/device-upgrade/DeviceFirmwareUpgradeModal.vue')['default']
    DeviceHmsDrawer: typeof import('./src/components/devices/device-hms/DeviceHmsDrawer.vue')['default']
    DeviceLogDetailModal: typeof import('./src/components/devices/device-log/DeviceLogDetailModal.vue')['default']
    DeviceLogUploadModal: typeof import('./src/components/devices/device-log/DeviceLogUploadModal.vue')['default']
    DeviceLogUploadRecordDrawer: typeof import('./src/components/devices/device-log/DeviceLogUploadRecordDrawer.vue')['default']
    DeviceSettingBox: typeof import('./src/components/g-map/DeviceSettingBox.vue')['default']
    DeviceSettingPopover: typeof import('./src/components/g-map/DeviceSettingPopover.vue')['default']
    DividerLine: typeof import('./src/components/workspace/DividerLine.vue')['default']
    DockControlPanel: typeof import('./src/components/g-map/DockControlPanel.vue')['default']
    DroneControlInfoPanel: typeof import('./src/components/g-map/DroneControlInfoPanel.vue')['default']
    DroneControlPanel: typeof import('./src/components/g-map/DroneControlPanel.vue')['default']
    DroneControlPopover: typeof import('./src/components/g-map/DroneControlPopover.vue')['default']
    FlightAreaActionIcon: typeof import('./src/components/flight-area/FlightAreaActionIcon.vue')['default']
    FlightAreaDevicePanel: typeof import('./src/components/flight-area/FlightAreaDevicePanel.vue')['default']
    FlightAreaIcon: typeof import('./src/components/flight-area/FlightAreaIcon.vue')['default']
    FlightAreaItem: typeof import('./src/components/flight-area/FlightAreaItem.vue')['default']
    FlightAreaPanel: typeof import('./src/components/flight-area/FlightAreaPanel.vue')['default']
    FlightAreaSyncPanel: typeof import('./src/components/flight-area/FlightAreaSyncPanel.vue')['default']
    GMap: typeof import('./src/components/GMap.vue')['default']
    IndexBak: typeof import('./src/components/land/add-land-form-modal/index-bak.vue')['default']
    LayersTree: typeof import('./src/components/LayersTree.vue')['default']
    Leftbar: typeof import('./src/components/common/leftbar.vue')['default']
    LivestreamAgora: typeof import('./src/components/livestream-agora.vue')['default']
    LivestreamOthers: typeof import('./src/components/livestream-others.vue')['default']
    MediaPanel: typeof import('./src/components/MediaPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/common/sidebar.vue')['default']
    SvgIcon: typeof import('./src/components/svgIcon.vue')['default']
    TaskPanel: typeof import('./src/components/task/TaskPanel.vue')['default']
    Title: typeof import('./src/components/workspace/Title.vue')['default']
    Topbar: typeof import('./src/components/common/topbar.vue')['default']
    TopbarNew: typeof import('./src/components/common/topbar-new.vue')['default']
  }
}
